-- Add typography settings table for global font management
create table if not exists public.typography_settings (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  
  -- Font families
  heading_font text not null default 'var(--font-playfair)',
  body_font text not null default 'var(--font-inter)',
  accent_font text not null default 'var(--font-playfair)',
  
  -- Heading styles
  h1_font_size text not null default 'clamp(2rem, 4vw, 3rem)',
  h1_font_weight text not null default '400',
  h1_line_height text not null default '1.1',
  h1_letter_spacing text not null default '-0.02em',
  
  h2_font_size text not null default 'clamp(1.5rem, 3vw, 2rem)',
  h2_font_weight text not null default '400',
  h2_line_height text not null default '1.2',
  h2_letter_spacing text not null default '-0.01em',
  
  h3_font_size text not null default 'clamp(1.25rem, 2.5vw, 1.5rem)',
  h3_font_weight text not null default '400',
  h3_line_height text not null default '1.3',
  h3_letter_spacing text not null default '0',
  
  h4_font_size text not null default 'clamp(1.125rem, 2vw, 1.25rem)',
  h4_font_weight text not null default '400',
  h4_line_height text not null default '1.4',
  h4_letter_spacing text not null default '0',
  
  -- Body text styles
  body_font_size text not null default 'clamp(1rem, 2vw, 1.125rem)',
  body_font_weight text not null default '400',
  body_line_height text not null default '1.6',
  body_letter_spacing text not null default '0',
  
  body_large_font_size text not null default 'clamp(1.125rem, 2vw, 1.25rem)',
  body_large_font_weight text not null default '400',
  body_large_line_height text not null default '1.6',
  body_large_letter_spacing text not null default '0',
  
  small_font_size text not null default 'clamp(0.875rem, 1.5vw, 1rem)',
  small_font_weight text not null default '400',
  small_line_height text not null default '1.5',
  small_letter_spacing text not null default '0',
  
  -- Label/Button styles
  label_font_size text not null default 'clamp(0.6875rem, 1.125vw, 0.75rem)',
  label_font_weight text not null default '500',
  label_line_height text not null default '1.4',
  label_letter_spacing text not null default '0.15em',
  label_text_transform text not null default 'uppercase',
  
  button_font_size text not null default 'clamp(0.6875rem, 1.125vw, 0.75rem)',
  button_font_weight text not null default '500',
  button_line_height text not null default '1.4',
  button_letter_spacing text not null default '0.15em',
  button_text_transform text not null default 'uppercase',
  
  caption_font_size text not null default 'clamp(0.75rem, 1.25vw, 0.875rem)',
  caption_font_weight text not null default '500',
  caption_line_height text not null default '1.4',
  caption_letter_spacing text not null default '0.15em',
  caption_text_transform text not null default 'uppercase',
  
  -- Display/Hero styles
  display_font_size text not null default 'clamp(2.5rem, 5vw, 4rem)',
  display_font_weight text not null default '400',
  display_line_height text not null default '1.1',
  display_letter_spacing text not null default '-0.02em'
);

-- Create index for easy lookup
create index if not exists typography_settings_id_idx
on public.typography_settings(id);

-- Insert default settings if table is empty
insert into public.typography_settings (
  heading_font,
  body_font,
  accent_font,
  h1_font_size,
  h1_font_weight,
  h1_line_height,
  h1_letter_spacing,
  h2_font_size,
  h2_font_weight,
  h2_line_height,
  h2_letter_spacing,
  h3_font_size,
  h3_font_weight,
  h3_line_height,
  h3_letter_spacing,
  h4_font_size,
  h4_font_weight,
  h4_line_height,
  h4_letter_spacing,
  body_font_size,
  body_font_weight,
  body_line_height,
  body_letter_spacing,
  body_large_font_size,
  body_large_font_weight,
  body_large_line_height,
  body_large_letter_spacing,
  small_font_size,
  small_font_weight,
  small_line_height,
  small_letter_spacing,
  label_font_size,
  label_font_weight,
  label_line_height,
  label_letter_spacing,
  label_text_transform,
  button_font_size,
  button_font_weight,
  button_line_height,
  button_letter_spacing,
  button_text_transform,
  caption_font_size,
  caption_font_weight,
  caption_line_height,
  caption_letter_spacing,
  caption_text_transform,
  display_font_size,
  display_font_weight,
  display_line_height,
  display_letter_spacing
) select 
  'var(--font-playfair)',
  'var(--font-inter)',
  'var(--font-playfair)',
  'clamp(2rem, 4vw, 3rem)',
  '400',
  '1.1',
  '-0.02em',
  'clamp(1.5rem, 3vw, 2rem)',
  '400',
  '1.2',
  '-0.01em',
  'clamp(1.25rem, 2.5vw, 1.5rem)',
  '400',
  '1.3',
  '0',
  'clamp(1.125rem, 2vw, 1.25rem)',
  '400',
  '1.4',
  '0',
  'clamp(1rem, 2vw, 1.125rem)',
  '400',
  '1.6',
  '0',
  'clamp(1.125rem, 2vw, 1.25rem)',
  '400',
  '1.6',
  '0',
  'clamp(0.875rem, 1.5vw, 1rem)',
  '400',
  '1.5',
  '0',
  'clamp(0.6875rem, 1.125vw, 0.75rem)',
  '500',
  '1.4',
  '0.15em',
  'uppercase',
  'clamp(0.6875rem, 1.125vw, 0.75rem)',
  '500',
  '1.4',
  '0.15em',
  'uppercase',
  'clamp(0.75rem, 1.25vw, 0.875rem)',
  '500',
  '1.4',
  '0.15em',
  'uppercase',
  'clamp(2.5rem, 5vw, 4rem)',
  '400',
  '1.1',
  '-0.02em'
where not exists (select 1 from public.typography_settings);
